"""empty message

Revision ID: 08beb4609a7d
Revises: 63ae407730e7
Create Date: 2024-09-30 20:01:02.353092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08beb4609a7d'
down_revision = '63ae407730e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engine', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('engine')

    # ### end Alembic commands ###
