"""empty message

Revision ID: 14382d5a26a5
Revises: 
Create Date: 2024-09-27 17:37:47.430754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '14382d5a26a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Items',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Description', sa.VARCHAR(length=500, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Priority', sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('Active', mssql.BIT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK__Items__3214EC07C800FB35')
    )
    op.drop_table('item')
    # ### end Alembic commands ###
