"""empty message

Revision ID: 5163e80d12d4
Revises: ebf44c4308b6
Create Date: 2024-09-30 19:17:35.733156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5163e80d12d4'
down_revision = 'ebf44c4308b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(collation='Latin1_General_CI_AS'),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(collation='Latin1_General_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
