"""empty message

Revision ID: 63ae407730e7
Revises: e94b0cd72173
Create Date: 2024-09-30 19:50:18.824971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ae407730e7'
down_revision = 'e94b0cd72173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('image1',
               existing_type=sa.VARCHAR(length=500, collation='Latin1_General_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('image2',
               existing_type=sa.VARCHAR(length=500, collation='Latin1_General_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('image3',
               existing_type=sa.VARCHAR(length=500, collation='Latin1_General_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('image3',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500, collation='Latin1_General_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('image2',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500, collation='Latin1_General_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('image1',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500, collation='Latin1_General_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
