"""empty message

Revision ID: 67d862d0a64b
Revises: f77cd884b902
Create Date: 2024-09-29 15:55:28.789920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d862d0a64b'
down_revision = 'f77cd884b902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.Text(), nullable=False))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=500, collation='Latin1_General_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500, collation='Latin1_General_CI_AS'),
               existing_nullable=True)
        batch_op.drop_column('mimetype')

    # ### end Alembic commands ###
