"""empty message

Revision ID: 7886ba2fe762
Revises: 67d862d0a64b
Create Date: 2024-09-29 16:26:01.705676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7886ba2fe762'
down_revision = '67d862d0a64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.alter_column('mimetype',
               existing_type=sa.VARCHAR(collation='Latin1_General_CI_AS'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.alter_column('mimetype',
               existing_type=sa.VARCHAR(collation='Latin1_General_CI_AS'),
               nullable=False)

    # ### end Alembic commands ###
