"""empty message

Revision ID: c64d492c75c9
Revises: 7886ba2fe762
Create Date: 2024-09-30 17:00:44.188341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64d492c75c9'
down_revision = '7886ba2fe762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephone', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('telephone')

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('mileage')

    # ### end Alembic commands ###
