"""empty message

Revision ID: e94b0cd72173
Revises: e5502c4b2d26
Create Date: 2024-09-30 19:36:33.776546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'e94b0cd72173'
down_revision = 'e5502c4b2d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_column('binImage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('binImage', mssql.VARBINARY(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
